# copy this file to "application.yaml" beside your jar file and change parameters you need
# you can delete not needed options (they default to whats here compiled in)
app:
    ldap:
        # make a ssh tunnel to your LDAP Server
        url: ldap://localhost:3389
        base: dc=chaostreff-dortmund,dc=de
        userDn: cn=selfservice,ou=admins,dc=chaostreff-dortmund,dc=de
        password:

    email:
        from: no-reply@example.com
        subject: "Self Service: New User"
        to: mail@example.com
    shells: /bin/bash,/bin/dash,/bin/false,/bin/sh,/bin/tcsh,/bin/zsh,/usr/bin/fish
    defaultGID: 2000
    userOU: people

spring:
    mail:
        # make a ssh tunnel to your SMTP Server
        host: localhost
        port: 2222
    thymeleaf:
            cache: false
    jackson:
        serialization:
            indent_output: true
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    mvc:
        favicon:
            enabled: false
